# Site settings
title: montsuqi.org
timezone: Asia/Tokyo
description: MONTSUQIと、その関連パッケージに関する情報を提供するウェブサイトです。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://montsuqi.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
